### ISSUE TITLE
v3.1.0 - Error: Failed to resolve entry for package "@swup/body-class-plugin".

### ISSUE THREAD

**Issue by NikolaRHristov** [swup/body-class-plugin#24]
The package may have incorrect main/module/exports specified in its package.json.

```ts
16:35:16.524 | [commonjs--resolver] Failed to resolve entry for package "@swup/body-class-plugin". The package may have incorrect main/module/exports specified in its package.json.
-- | --
16:35:16.813 | error   Failed to resolve entry for package "@swup/body-class-plugin". The package may have incorrect main/module/exports specified in its package.json.
16:35:16.813 | File:
16:35:16.813 | /opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28708:11
16:35:16.814 | Code:
16:35:16.814 | 28707 \| function packageEntryFailure(id, details) {
16:35:16.814 | > 28708 \|     throw new Error(`Failed to resolve entry for package "${id}". ` +
16:35:16.814 | \|           ^
16:35:16.814 | 28709 \|         `The package may have incorrect main/module/exports specified in its package.json` +
16:35:16.814 | 28710 \|         (details ? ': ' + details : '.'));
16:35:16.814 | 28711 \| }
16:35:16.815 | Stacktrace:
16:35:16.815 | Error: Failed to resolve entry for package "@swup/body-class-plugin". The package may have incorrect main/module/exports specified in its package.json.
16:35:16.815 | at packageEntryFailure (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28708:11)
16:35:16.815 | at resolvePackageEntry (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28705:5)
16:35:16.815 | at tryNodeResolve (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28436:20)
16:35:16.815 | at Object.resolveId (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28197:28)
16:35:16.815 | at file:///opt/buildhome/repo/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:25356:40
16:35:16.815 | at async PluginDriver.hookFirstAndGetPlugin (file:///opt/buildhome/repo/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:25256:28)
16:35:16.815 | at async resolveId (file:///opt/buildhome/repo/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:23931:26)
16:35:16.816 | at async ModuleLoader.resolveId (file:///opt/buildhome/repo/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24345:15)
16:35:16.816 | at async Object.resolveId (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:7984:10)
16:35:16.816 | at async PluginDriver.hookFirstAndGetPlugin (file:///opt/buildhome/repo/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:25256:28)
16:35:16.816 |  
16:35:16.848 | Failed: build command exited with code: 1
16:35:17.750 | Failed: error occurred while running build command
```

This happens when deploying in an Astro website on Cloudflare. Here's an example https://github.com/MythemeCloud/mytheme-web

**Comment by hirasso** [comment]
Thanks for reporting this! Seems like the `dist` folder went missing in the latest release. Let me look into it.

**Comment by hirasso** [comment]
Should be fixed in these both versions:
```json
{
	"@swup/body-class-plugin": "^3.1.1",
	"@swup/head-plugin": "^2.1.1",
}
```
I'll check all the other recently released plugins. Thanks again for the heads-up!! 🙏

**Comment by NikolaRHristov** [comment]
Thank you so much for fixing this!
